### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by yanmofeixi** [IBM5100o/HDT_BGrank#2]
16:19:39|Error|BGrank.GetOppNames >> System.NullReferenceException: 未将对象引用设置到对象的实例。
在 HDT_BGrank.BGrank.GetOppNames()

Happens occasionally.

**Comment by IBM5100o** [comment]
Maybe fixed in v1.1.7.
Still not sure about that.

**Comment by Jordan-Sun** [comment]
Might be the same issue:
9:26:07 PM|Error|BGrank.GetOppNames >> Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: Cannot perform runtime binding on a null reference
   at CallSite.Target(Closure , CallSite , Object , String )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
   at CallSite.Target(Closure , CallSite , Object , String )
   at HDT_BGrank.BGrank.GetPlayerTiles(Object leaderboardMgr)
   at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
   at CallSite.Target(Closure , CallSite , BGrank , Object )
   at HDT_BGrank.BGrank.GetOppNames()
9:26:08 PM|Error|BGrank.GetOppNames >> Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: Cannot perform runtime binding on a null reference
   at CallSite.Target(Closure , CallSite , Object , String )
   at HDT_BGrank.BGrank.GetPlayerTiles(Object leaderboardMgr)
   at HDT_BGrank.BGrank.GetOppNames()

**Comment by IBM5100o** [comment]
I change the timing to get hearthstone memory image, and check if the data structure is the old one (before duos update).
The probability of this error to occur should be lower now (v1.1.8), but might not be fixed totally.
And thanks for reporting.
